name: ritmos_de_violao_premium
description: Ritmos de violão premium

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.6
  font_awesome_flutter: ^10.2.1
  share_plus: ^9.0.0
  package_info_plus: ^8.0.0
  pod_player: ^0.2.2
  auto_size_text: ^3.0.0
  cached_network_image:
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  firebase_core:
  firebase_storage: ^11.2.3
  cloud_firestore: ^4.8.1
  shimmer: ^3.0.0
  rxdart: ^0.27.5
  localstorage: ^5.0.0
  mask_text_input_formatter: ^2.3.0
  validators: ^3.0.0
  brasil_fields: ^1.3.1
  purchases_flutter:
  provider:
  webview_flutter: ^4.2.2
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  change_app_package_name:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icone/
    - assets/imagens/icone_botao_play.svg
    - assets/imagens/play.png
    - assets/imagens/icone_olho_fechado.svg
    - assets/imagens/icone_olho.svg
    - assets/capa_ofertas/
    - assets/canal/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Co Headline Bold
      fonts:
        - asset: assets/fonts/Co Headline Bold.ttf
    - family: Co Headline Light
      fonts:
        - asset: assets/fonts/Co Headline Corp Light.ttf
    - family: Co Headline W01 Regular
      fonts:
        - asset: assets/fonts/Co Headline W01 Regular.ttf
    - family: Mulish Regular
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
    - family: Mulish Bold
      fonts:
        - asset: assets/fonts/Mulish-Bold.ttf
    - family: Mulish SemiBold
      fonts:
        - asset: assets/fonts/Mulish-SemiBold.ttf
    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: Montserrat Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
